name: module3_task0
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
on: [push]
jobs:
jobs:
  module3_task0:
  module3_task0:
    runs-on: ubuntu-18.04
    runs-on: ubuntu-latest
    steps:
    steps:
      - name: Checkout
      - name: Checkout
        uses: actions/checkout
        uses: actions/checkout
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: cd in to correct directory
        run: |
          cd ${{ github.workspace}}
